In [1]:
import pandas as pd

df=pd.read_csv("sample.csv")
print(df.head())

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

In [2]:
import pandas as pd

df=pd.read_csv("sample.csv")
print(df.tail())

   No       Name  Type1   Type2  Height  Weight  Legendary
5   6  Charizard   Fire  Flying     1.7    90.5          0
6   7   Squirtle  Water     NaN     0.5     9.0          0
7   8  Wartortle  Water     NaN     1.0    22.5          0
8   9  Blastoise  Water     NaN     1.6    85.5          0
9  10   Caterpie    Bug     NaN     0.3     2.9          0

In [3]:
import pandas as pd

df=pd.read_csv("sample.csv")
print(df.head(3))

   No       Name  Type1   Type2  Height  Weight  Legendary
0   1  Bulbasaur  Grass  Poison     0.7     6.9          0
1   2    Ivysaur  Grass  Poison     1.0    13.0          0
2   3   Venusaur  Grass  Poison     2.0   100.0          0

In [5]:
import pandas as pd

df=pd.read_csv("sample.csv")
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         10 non-null     int64
 1   Name       10 non-null     str
 2   Type1      10 non-null     str
 3   Type2      4 non-null      str
 4   Height     10 non-null     float64
 5   Weight     10 non-null     float64
 6   Legendary  10 non-null     int64
dtypes: float64(2), int64(2), str(3)
memory usage: 692.0 bytes
None

In [6]:
import pandas as pd

df=pd.read_csv("sample.csv")
print(df.iloc[0:3])

   No       Name  Type1   Type2  Height  Weight  Legendary
0   1  Bulbasaur  Grass  Poison     0.7     6.9          0
1   2    Ivysaur  Grass  Poison     1.0    13.0          0
2   3   Venusaur  Grass  Poison     2.0   100.0          0

In [8]:
import pandas as pd

df=pd.read_csv("sample.csv")
df.sort_values("Weight")

   No        Name  Type1   Type2  Height  Weight  Legendary
9  10    Caterpie    Bug     NaN     0.3     2.9          0
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
6   7    Squirtle  Water     NaN     0.5     9.0          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0
7   8   Wartortle  Water     NaN     1.0    22.5          0
8   9   Blastoise  Water     NaN     1.6    85.5          0
5   6   Charizard   Fire  Flying     1.7    90.5          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0

In [9]:
import pandas as pd

df=pd.read_csv("sample.csv")
df.isna()

      No   Name  Type1  Type2  Height  Weight  Legendary
0  False  False  False  False   False   False      False
1  False  False  False  False   False   False      False
2  False  False  False  False   False   False      False
3  False  False  False   True   False   False      False
4  False  False  False   True   False   False      False
5  False  False  False  False   False   False      False
6  False  False  False   True   False   False      False
7  False  False  False   True   False   False      False
8  False  False  False   True   False   False      False
9  False  False  False   True   False   False      False

In [12]:
import pandas as pd

df=pd.read_csv("sample.csv")
del df["Weight"]
print(df)

   No        Name  Type1   Type2  Height  Legendary
0   1   Bulbasaur  Grass  Poison     0.7          0
1   2     Ivysaur  Grass  Poison     1.0          0
2   3    Venusaur  Grass  Poison     2.0          0
3   4  Charmander   Fire     NaN     0.6          0
4   5  Charmeleon   Fire     NaN     1.1          0
5   6   Charizard   Fire  Flying     1.7          0
6   7    Squirtle  Water     NaN     0.5          0
7   8   Wartortle  Water     NaN     1.0          0
8   9   Blastoise  Water     NaN     1.6          0
9  10    Caterpie    Bug     NaN     0.3          0

In [15]:

import pandas as pd

df=pd.read_csv("sample.csv")
df.fillna({
    "Type2": "None"
})

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire    None     0.6     8.5          0
4   5  Charmeleon   Fire    None     1.1    19.0          0
5   6   Charizard   Fire  Flying     1.7    90.5          0
6   7    Squirtle  Water    None     0.5     9.0          0
7   8   Wartortle  Water    None     1.0    22.5          0
8   9   Blastoise  Water    None     1.6    85.5          0
9  10    Caterpie    Bug    None     0.3     2.9          0

In [29]:
import pandas as pd

df=pd.read_csv("sample.csv")
df.drop(
    index=[9]
)

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0
5   6   Charizard   Fire  Flying     1.7    90.5          0
6   7    Squirtle  Water     NaN     0.5     9.0          0
7   8   Wartortle  Water     NaN     1.0    22.5          0
8   9   Blastoise  Water     NaN     1.6    85.5          0

In [31]:
import pandas as pd

df=pd.read_csv("sample.csv")
df.drop(
    columns=["Legendary"]
)

   No        Name  Type1   Type2  Height  Weight
0   1   Bulbasaur  Grass  Poison     0.7     6.9
1   2     Ivysaur  Grass  Poison     1.0    13.0
2   3    Venusaur  Grass  Poison     2.0   100.0
3   4  Charmander   Fire     NaN     0.6     8.5
4   5  Charmeleon   Fire     NaN     1.1    19.0
5   6   Charizard   Fire  Flying     1.7    90.5
6   7    Squirtle  Water     NaN     0.5     9.0
7   8   Wartortle  Water     NaN     1.0    22.5
8   9   Blastoise  Water     NaN     1.6    85.5
9  10    Caterpie    Bug     NaN     0.3     2.9

In [32]:


import pandas as pd

df=pd.read_csv("sample.csv")
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         10 non-null     int64
 1   Name       10 non-null     str
 2   Type1      10 non-null     str
 3   Type2      4 non-null      str
 4   Height     10 non-null     float64
 5   Weight     10 non-null     float64
 6   Legendary  10 non-null     int64
dtypes: float64(2), int64(2), str(3)
memory usage: 692.0 bytes
None

In [33]:
import pandas as pd

df=pd.read_csv("sample.csv")
print(df.describe())

             No     Height      Weight  Legendary
count  10.00000  10.000000   10.000000       10.0
mean    5.50000   1.050000   35.780000        0.0
std     3.02765   0.560258   39.361481        0.0
min     1.00000   0.300000    2.900000        0.0
25%     3.25000   0.625000    8.625000        0.0
50%     5.50000   1.000000   16.000000        0.0
75%     7.75000   1.475000   69.750000        0.0
max    10.00000   2.000000  100.000000        0.0

In [35]:
import pandas as pd

df=pd.read_csv("sample.csv")
df.shape

(10, 7)